import glob

"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['run_client.py']
DATA_FILES = [
  ('resources', glob.glob('resources/*')),
]
OPTIONS = {
  'includes': ['imp'],
  'plist': {'LSUIElement': True},
}

setup(
  app=APP,
  name='MeetingStatus',
  data_files=DATA_FILES,
  options={'py2app': OPTIONS},
  setup_requires=['py2app'],
)
